/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.app;

import estructurasLineales.operaciones.ListaOrden;
import grafic.Inicio;
import java.awt.Dimension;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author ednux
 */
public class ListaOrdenada extends javax.swing.JInternalFrame {
    
    Inicio in = new Inicio();

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension DimensionBarra = null;
    ListaOrden list = new ListaOrden();

    public void QuitarLaBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        DimensionBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }

    public void agregar() {
        if (this.textDato.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "el campo esta vacio ");
            this.textDato.requestFocus();
        } else {
            this.list.insertarDato(Integer.parseInt(this.textDato.getText()));
            this.textEstado.setText(String.valueOf(this.list.mostrar()));
            this.textDato.setText("");
            this.textDato.requestFocus();
        }
    }

    public void eliminar() {
        if (this.list.estaVacia() == true) {
            JOptionPane.showMessageDialog(null, "la lista esta vacia");
            this.textDato.requestFocus();
        } else {
            if (this.textDato.getText().equals("")) {
                //JOptionPane.showMessageDialog(null, "case 1");
                this.textElimiando.setText(String.valueOf(this.list.first()));
                this.list.eliminarDato();
                this.textEstado.setText(String.valueOf(this.list.mostrar()));
                this.textDato.requestFocus();
            } else if (this.list.buscarDato(Integer.parseInt(this.textDato.getText())) == true) {
                //JOptionPane.showMessageDialog(null, "case 3");
                String datoActual = this.textDato.getText();
                this.textElimiando.setText(datoActual);
                this.list.deletedd(Integer.parseInt(this.textDato.getText()));
                this.textEstado.setText(String.valueOf(this.list.mostrar()));
                this.textDato.setText("");
                this.textDato.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "el dato no existe");
                this.textDato.setText("");
                this.textDato.requestFocus();
            }
        }
    }

    /**
     * Creates new form ListaOrdenada
     */
    public ListaOrdenada() {
        initComponents();
        QuitarLaBarraTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textDato = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        textEstado = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        textElimiando = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 216, 157));
        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textDato.setBackground(new java.awt.Color(255, 255, 255));
        textDato.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textDato.setForeground(new java.awt.Color(102, 102, 102));
        textDato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDato.setBorder(null);
        textDato.setOpaque(false);
        getContentPane().add(textDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 120, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, 40));

        textEstado.setBackground(new java.awt.Color(255, 255, 255));
        textEstado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textEstado.setForeground(new java.awt.Color(51, 51, 51));
        textEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textEstado.setBorder(null);
        textEstado.setOpaque(false);
        getContentPane().add(textEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 50));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 200, 10));

        textElimiando.setBackground(new java.awt.Color(255, 255, 255));
        textElimiando.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textElimiando.setForeground(new java.awt.Color(102, 102, 102));
        textElimiando.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textElimiando.setBorder(null);
        textElimiando.setOpaque(false);
        getContentPane().add(textElimiando, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 80, 50));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("AGREGRAR");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("ELIMINAR");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 51, 0)));
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 180, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 0));
        jButton3.setText("CERRAR");
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 180, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Dato Eliminado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 190, 140, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Estado Lista");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Dato");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafic/app/img/fondoapp5.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(230, 445));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.in.limpiar();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField textDato;
    private javax.swing.JTextField textElimiando;
    private javax.swing.JTextField textEstado;
    // End of variables declaration//GEN-END:variables
}
