/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import grafo.GrafoApp;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class VentanaGrafo extends javax.swing.JFrame {

    GrafoApp app = new GrafoApp();

    /**
     * Creates new form VentanaGrafo
     */
    public VentanaGrafo() {
        initComponents();
    }

    public void agregar() {
        if (this.textDatoLista.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "el Campo esta Vacio ");
            this.textDatoLista.setText("");
            this.textDatoLista.requestFocus(true);

        } else {
            if (this.app.buscarDatoLista(Integer.parseInt(this.textDatoLista.getText())) == false) {

                this.app.agregarLista(Integer.parseInt(this.textDatoLista.getText()));
           
              
                this.textDatoLista.setText("");
                this.textDatoLista.requestFocus(true);
                                this.textEstado.setText(app.mostrar());


            } else {

                JOptionPane.showMessageDialog(null, "Dato ya existente");
                this.textDatoLista.setText("");
                this.textDatoLista.requestFocus(true);
            }

        }

    }

    public void agregarA() {
        this.textEstado.setText(app.mostrar());
        this.app.agregarDerecha(Integer.parseInt(this.textNodo.getText()), Integer.parseInt(this.textDatoA.getText()));
        this.textEstado.setText(app.mostrar());
        this.textDatoA.setText("");
        this.textDatoA.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textDatoLista = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        textDatoA = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textEstado = new javax.swing.JTextArea();
        textNodo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Grafo ");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textDatoLista.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        textDatoLista.setForeground(new java.awt.Color(102, 102, 102));
        textDatoLista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDatoLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dato :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andale Mono", 0, 12))); // NOI18N
        textDatoLista.setFocusTraversalKeysEnabled(false);
        textDatoLista.setMaximumSize(new java.awt.Dimension(12, 43));
        textDatoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDatoListaActionPerformed(evt);
            }
        });
        jPanel1.add(textDatoLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, -1));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Agregar Lista ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("AppleMyungjo", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Agregar");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, -1));

        jLabel2.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Agregar Adyacente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 270, -1));

        textDatoA.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        textDatoA.setForeground(new java.awt.Color(102, 102, 102));
        textDatoA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textDatoA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dato :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Apple SD Gothic Neo", 0, 12))); // NOI18N
        jPanel1.add(textDatoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, 60));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 90, 20));

        jButton1.setFont(new java.awt.Font("AppleMyungjo", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Agregar");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 100, 40));

        textEstado.setColumns(20);
        textEstado.setRows(5);
        jScrollPane1.setViewportView(textEstado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 300, 360));

        textNodo.setFont(new java.awt.Font("AppleGothic", 0, 15)); // NOI18N
        textNodo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNodoActionPerformed(evt);
            }
        });
        jPanel1.add(textNodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 110, 30));

        jLabel3.setText("NODO :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDatoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDatoListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDatoListaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        agregarA();
        this.textEstado.setText(app.mostrar());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGrafo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField textDatoA;
    private javax.swing.JTextField textDatoLista;
    private javax.swing.JTextArea textEstado;
    private javax.swing.JTextField textNodo;
    // End of variables declaration//GEN-END:variables
}
